#! /bin/sh

set +e

git checkout gh-pages
rm -rf book
cp -r _build/html/ book
cp -r _build/latex/theoretical-physics.pdf book/
# not necessary any more:
#cd book
#sphinx-to-github .
#cd ..
git add book
git commit -a -m "Automatic commit"
git checkout master
