name: Theoretical Physics Reference

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: Conda info
        shell: bash -l {0}
        run: |
            conda info
            conda list

      - name: Build html
        shell: bash -l {0}
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng latexmk autotools-dev libkpathsea-dev libfreetype6-dev libgs-dev libz-dev g++ make python-lxml python-pip python-setuptools git autotools-dev automake autoconf libtool
            sudo pip install "sphinx==1.7.6"
            bin/test_travis.sh
